server:
  address: 127.0.0.1
  port: 8080
  error:
    include-message: always

spring:
  h2:
    console:
        enabled: true
        path: /h2-console
  datasource:
    url: jdbc:h2:mem:foodOrderingSystemDb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: false
  main:
      banner-mode: off